version: '3.7'
services:

    php-apache:
      build: .
      ports:
        - 8080:80
      networks:
        - internal

    nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      networks:
        - internal

    postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: ${PS_USERNAME}
      POSTGRES_PASSWORD: ${PS_PASSWORD}
      PGDATA: ${PS_DB}
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - ${PS_DB}:/var/lib/postgresql/data/
    networks:
      - internal

    redis:
    image: redis:5.0.14
    ports:
      - 6379:6379
    networks:
      - internal

networks:
  internal:
    driver: bridge
